"use client";   
import { createContext, useContext, useState } from "react";
import "./globals.css";
import { Inter , Roboto, Poppins } from "next/font/google";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const = Intern({ subsets : ["latin"]})   

export const metadata =- {
    title : "Create Next App",
    description : "Generated by create next app",

}

